import type { Persona } from './types';

export const PERSONAS: Persona[] = [
  {
    id: 'hyeonwoo', name: '현우', nameEn: 'Hyeonwoo',
    archetype: '미닝아웃 청년', gen: 'Z', age: 24, sex: 'M',
    household: '부모동거', householdCode: 'parents',
    region: '수도권', occupation: '스타트업 인턴 · 환경 동아리',
    income: 2500000, savings_rate: 0.05, debt: '없음',
    values: { gaseong: 0.30, gasim: 0.45, meaning: 0.85, brand: 0.25 },
    lifestyle: { monitor_interest: 0.40, cosmetics_interest: 0.55 },
    bio: '환경·동물복지·ESG 강한 가치 정렬. 인디 서스테이너블 브랜드, 중고 리퍼브 선호.',
    sources: 'KOSTAT 2024 사회조사 (가치관) · 대한상의 MZ ESG 선호도 64%+',
  },
  {
    id: 'sua', name: '수아', nameEn: 'Sua',
    archetype: '짠테크 학생', gen: 'Z', age: 22, sex: 'F',
    household: '기숙사', householdCode: 'single',
    region: '대전', occupation: '카이스트 학부생 + 과외',
    income: 1500000, savings_rate: 0.35, debt: '학자금대출 진행중',
    values: { gaseong: 0.85, gasim: 0.30, meaning: 0.45, brand: 0.15 },
    lifestyle: { monitor_interest: 0.60, cosmetics_interest: 0.50 },
    bio: '용돈+과외로 짠테크 실천. 가성비 + 미닝아웃 혼합 (지속가능 브랜드 가성비 선호).',
    sources: 'KOSTAT 가계동향 · KB 1인가구 2024 (Z세대 절약 트렌드)',
  },
  {
    id: 'chaerin', name: '채린', nameEn: 'Chaerin',
    archetype: '인플루언서 마케터', gen: 'Z', age: 26, sex: 'F',
    household: '1인', householdCode: 'single',
    region: '서울 (성수)', occupation: '뷰티 인플루언서 · 마케팅 에이전시',
    income: 4200000, savings_rate: 0.08, debt: '신용카드 리볼빙 일부',
    values: { gaseong: 0.15, gasim: 0.90, meaning: 0.50, brand: 0.65 },
    lifestyle: { monitor_interest: 0.25, cosmetics_interest: 0.95 },
    bio: '플렉스·SNS 노출 중심 소비. 신상 화장품·향수 즉각 구매. 모니터·가전 거의 무관심.',
    sources: 'KPMG 2024 Liquid Consumption · 오픈서베이 MZ 화장품 패턴',
  },
  {
    id: 'minjun', name: '민준', nameEn: 'Minjun',
    archetype: '가성비 직장인', gen: 'M', age: 31, sex: 'M',
    household: '1인', householdCode: 'single',
    region: '서울 (강남)', occupation: 'IT 회사 백엔드 개발자 5년차',
    income: 3800000, savings_rate: 0.25, debt: '학자금대출 잔여 800만원',
    values: { gaseong: 0.85, gasim: 0.20, meaning: 0.15, brand: 0.20 },
    lifestyle: { monitor_interest: 0.90, cosmetics_interest: 0.05 },
    bio: '게임 PC·모니터·기계식 키보드 자주 교체. 리뷰·스펙 비교 광적. 화장품 거의 무관심.',
    sources: 'KOSTAT 가계동향 3분위 · KB 1인가구 평균소득 3,423만원',
  },
  {
    id: 'seojin', name: '서진', nameEn: 'Seojin',
    archetype: '가심비 워커', gen: 'M', age: 28, sex: 'F',
    household: '1인', householdCode: 'single',
    region: '서울 (홍대)', occupation: '마케팅 에이전시 어카운트 매니저',
    income: 4200000, savings_rate: 0.18, debt: '없음',
    values: { gaseong: 0.25, gasim: 0.85, meaning: 0.30, brand: 0.55 },
    lifestyle: { monitor_interest: 0.30, cosmetics_interest: 0.85 },
    bio: 'K-뷰티 enthusiast. 화장품·향수·디저트·여행 지출 큼. 가전은 그냥 쓸만하면 OK.',
    sources: 'KOSTAT 가계동향 3-4분위 · 소비자평가 (가심비 트렌드)',
  },
  {
    id: 'doyoon', name: '도윤', nameEn: 'Doyoon',
    archetype: '스타트업 CEO', gen: 'M', age: 36, sex: 'M',
    household: '1인', householdCode: 'single',
    region: '서울 (강남)', occupation: 'B2B SaaS 스타트업 대표',
    income: 7500000, savings_rate: 0.30, debt: '없음 (회사 지분 보유)',
    values: { gaseong: 0.20, gasim: 0.70, meaning: 0.65, brand: 0.50 },
    lifestyle: { monitor_interest: 0.85, cosmetics_interest: 0.45 },
    bio: '듀얼 모니터·기계식 키보드·프리미엄 헤드폰. 화장품은 미닝아웃 브랜드만.',
    sources: 'KOSTAT 가계동향 5분위 · KPMG 2024',
  },
  {
    id: 'minseo', name: '민서', nameEn: 'Minseo',
    archetype: 'DINK 와이프', gen: 'M', age: 33, sex: 'F',
    household: 'DINK 부부', householdCode: 'dink',
    region: '경기 분당', occupation: '제약 회사 마케팅 팀장',
    income: 5500000, savings_rate: 0.25, debt: '주담대 월 80만원',
    values: { gaseong: 0.30, gasim: 0.80, meaning: 0.50, brand: 0.60 },
    lifestyle: { monitor_interest: 0.40, cosmetics_interest: 0.75 },
    bio: '아이 대신 자기·반려동물 투자. 럭셔리 화장품 정기 구매, 가전은 가성비.',
    sources: 'KOSTAT 가계동향 (DINK 패턴) · KB 보고서',
  },
  {
    id: 'taehyun', name: '태현', nameEn: 'Taehyun',
    archetype: 'DINK 남편', gen: 'M', age: 35, sex: 'M',
    household: 'DINK 부부', householdCode: 'dink',
    region: '경기 분당', occupation: '대기업 R&D 책임연구원',
    income: 6800000, savings_rate: 0.28, debt: '주담대 (배우자 공동)',
    values: { gaseong: 0.45, gasim: 0.65, meaning: 0.40, brand: 0.55 },
    lifestyle: { monitor_interest: 0.75, cosmetics_interest: 0.40 },
    bio: '취미용 고급 모니터, 향수·스킨케어도 관심. 가전 신상 빠르게 교체.',
    sources: 'KOSTAT 가계동향 5분위 · BOK 이슈노트',
  },
  {
    id: 'jihye', name: '지혜', nameEn: 'Jihye',
    archetype: '균형 맞벌이맘', gen: 'M', age: 38, sex: 'F',
    household: '부부+자녀2', householdCode: 'family',
    region: '경기 동탄', occupation: '중견기업 차장 · 워킹맘',
    income: 4800000, savings_rate: 0.12, debt: '주담대 월 110만원',
    values: { gaseong: 0.70, gasim: 0.55, meaning: 0.35, brand: 0.40 },
    lifestyle: { monitor_interest: 0.50, cosmetics_interest: 0.55 },
    bio: '생필품은 가성비, 자녀 학용품·여행은 프리미엄. 본인 화장품은 중간.',
    sources: 'KOSTAT 가계동향 (4분위 가구) · 사교육비 18%',
  },
  {
    id: 'yunjeong', name: '윤정', nameEn: 'Yunjeong',
    archetype: '워킹맘 영업', gen: 'M', age: 41, sex: 'F',
    household: '부부+자녀2', householdCode: 'family',
    region: '인천', occupation: '제약 영업 차장',
    income: 5200000, savings_rate: 0.10, debt: '주담대 월 130만원',
    values: { gaseong: 0.75, gasim: 0.40, meaning: 0.30, brand: 0.45 },
    lifestyle: { monitor_interest: 0.35, cosmetics_interest: 0.60 },
    bio: '시간 부족으로 화장품은 동일 브랜드 반복. 가전은 무난·실용.',
    sources: 'KOSTAT 가계동향 (워킹맘) · KB 보고서',
  },
  {
    id: 'jongho', name: '종호', nameEn: 'Jongho',
    archetype: '절약 가장', gen: 'X', age: 45, sex: 'M',
    household: '부부+자녀2', householdCode: 'family',
    region: '인천', occupation: '제조업 중간관리자',
    income: 5500000, savings_rate: 0.05, debt: '주담대 월 130만원',
    values: { gaseong: 0.95, gasim: 0.10, meaning: 0.10, brand: 0.25 },
    lifestyle: { monitor_interest: 0.45, cosmetics_interest: 0.05 },
    bio: '모니터 5년 이상 사용. 화장품 카테고리 자체 거의 미사용.',
    sources: 'KOSTAT 가계동향 (외벌이 가장) · 통계청 2024 사회조사',
  },
  {
    id: 'seongho', name: '성호', nameEn: 'Seongho',
    archetype: '자영업자', gen: 'X', age: 48, sex: 'M',
    household: '부부+자녀1', householdCode: 'family',
    region: '서울', occupation: '카페 자영업자',
    income: 4500000, savings_rate: 0.08, debt: '사업자대출 + 주담대',
    values: { gaseong: 0.80, gasim: 0.35, meaning: 0.25, brand: 0.50 },
    lifestyle: { monitor_interest: 0.50, cosmetics_interest: 0.20 },
    bio: '가게 운영 모니터·POS 필수. 본인 화장품은 기본 브랜드만.',
    sources: 'KOSTAT 자영업자 가계동향',
  },
  {
    id: 'eunha', name: '은하', nameEn: 'Eunha',
    archetype: '전업주부', gen: 'X', age: 43, sex: 'F',
    household: '부부+자녀2', householdCode: 'family',
    region: '경기 수원', occupation: '전업주부 (前 회계사)',
    income: 0, savings_rate: 0.0, debt: '주담대 (배우자 명의)',
    values: { gaseong: 0.65, gasim: 0.55, meaning: 0.40, brand: 0.60 },
    lifestyle: { monitor_interest: 0.30, cosmetics_interest: 0.70 },
    bio: '가족 지출 통제권. 화장품은 백화점 브랜드, 가전은 가성비 비교 광적.',
    sources: 'KOSTAT 가계동향 (외벌이 가구 지출주체)',
  },
  {
    id: 'jeongsu', name: '정수', nameEn: 'Jeongsu',
    archetype: '시니어 부부', gen: 'Boomer', age: 62, sex: 'M',
    household: '부부 노년', householdCode: 'senior_couple',
    region: '서울 (강남)', occupation: '대기업 임원 은퇴 → 사외이사',
    income: 6500000, savings_rate: 0.40, debt: '없음 (자가)',
    values: { gaseong: 0.40, gasim: 0.55, meaning: 0.40, brand: 0.85 },
    lifestyle: { monitor_interest: 0.55, cosmetics_interest: 0.30 },
    bio: '브랜드 충성 강함. 익숙한 제품 고수. 가전·모니터는 신중·고가 선호.',
    sources: 'KOSTAT 사회조사 (60대 고소득) · BOK 자산보유 분포',
  },
  {
    id: 'yeongja', name: '영자', nameEn: 'Yeongja',
    archetype: '은퇴 1인가구', gen: 'Boomer', age: 68, sex: 'F',
    household: '1인 노년', householdCode: 'single',
    region: '부산', occupation: '은퇴 (前 자영업)',
    income: 1800000, savings_rate: 0.0, debt: '없음',
    values: { gaseong: 0.55, gasim: 0.30, meaning: 0.20, brand: 0.90 },
    lifestyle: { monitor_interest: 0.10, cosmetics_interest: 0.45 },
    bio: '국민연금 + 자녀 송금. 의료비 비중 큼. 화장품은 동일 브랜드 수십년 사용.',
    sources: 'KOSTAT 2025 1인가구 (노년 1인) · 한국은행 BOK 2024-31',
  },
  {
    id: 'mikyeong', name: '미경', nameEn: 'Mikyeong',
    archetype: '액티브 시니어', gen: 'Boomer', age: 64, sex: 'F',
    household: '부부 노년', householdCode: 'senior_couple',
    region: '서울 (서초)', occupation: '은퇴 (前 교사)',
    income: 3800000, savings_rate: 0.15, debt: '없음',
    values: { gaseong: 0.45, gasim: 0.60, meaning: 0.35, brand: 0.75 },
    lifestyle: { monitor_interest: 0.30, cosmetics_interest: 0.65 },
    bio: '연금 + 부동산 소득. 백화점 화장품·여행 적극. 가전은 보수적.',
    sources: 'KOSTAT 한국의 사회지표 2024 · 60대 액티브 시니어',
  },
];

export const VALUE_LABELS: Record<keyof import('./types').PersonaValues, string> = {
  gaseong: '가성비',
  gasim: '가심비',
  meaning: '미닝아웃',
  brand: '브랜드',
};

export function dominantValue(p: Persona): string {
  const entries = Object.entries(p.values) as Array<[keyof Persona['values'], number]>;
  entries.sort((a, b) => b[1] - a[1]);
  return VALUE_LABELS[entries[0][0]];
}
